name: D:\Documentos\Profesional\Dynamic_Flash\venv
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py38haa95532_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2021.3.0=haa95532_3372
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.2=py38hf11a4ad_0
  - numpy=1.20.3=py38ha4e8547_0
  - numpy-base=1.20.3=py38hc2deb75_0
  - openssl=1.1.1k=h2bbff1b_0
  - plotly=5.1.0=pyhd3eb1b0_0
  - python=3.8.11=h6244533_1
  - scipy=1.6.2=py38h66253e8_1
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tenacity=6.3.1=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - pip:
    - altair==4.1.0
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - base58==2.1.0
    - bleach==4.0.0
    - blinker==1.4
    - cachetools==4.2.2
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - click==7.1.2
    - colorama==0.4.4
    - debugpy==1.4.1
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - gekko==1.0.1
    - gitdb==4.0.7
    - gitpython==3.1.18
    - idna==3.2
    - ipykernel==6.0.3
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.2
    - packaging==21.0
    - pandas==1.3.1
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.3.1
    - pip==21.2.3
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - pyarrow==5.0.0
    - pycparser==2.20
    - pydeck==0.6.2
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywin32==301
    - pywinpty==1.1.3
    - pyzmq==22.2.1
    - requests==2.26.0
    - send2trash==1.8.0
    - smmap==4.0.0
    - streamlit==0.86.0
    - terminado==0.10.1
    - testpath==0.5.0
    - toml==0.10.2
    - toolz==0.11.1
    - tornado==6.1
    - traitlets==5.0.5
    - tzlocal==2.1
    - urllib3==1.26.6
    - validators==0.18.2
    - watchdog==2.1.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: D:\Documentos\Profesional\Dynamic_Flash\venv
